### ISSUE TITLE
Compare NHMD and Northtec metadata

### ISSUE THREAD

**Issue by ThomasAlscher1991** [NHMDenmark/DaSSCo-asset-service#1]
POST /v1/assetmetadata --> creates asset:
	metadata from NHMD .json is split up into 
	1. project metadata (PM) used as the minimal subset of information needed for creating the asset
	2. image metadata (IM) the carries information not needed for creating the asset

We need to check what metadata fields (or keys) are going into Northtec PM or IM.

**Comment by ThomasAlscher1991** [comment]
We should check if Northtec is deriving these from the post statement or not.

**Comment by bhsi-snm** [comment]
@PipBrewer thomas made a comparison of meta deta from northtech and your excel sheet, please ask northtech to comply with it

**Comment by PipBrewer** [comment]
@ThomasAlscher1991 Northetch's version is the one we want to use. We need to change our code to accomodate this.

**Comment by bhsi-snm** [comment]
@bhsi-snm will update the confluence meta data sheet and thomas@northtech will update the meta data fields accordingly for version 1
