### ISSUE TITLE
Northtech API issues -internal

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-asset-service#3]
[DocumentedIssuesForAPI.docx](https://github.com/NHMDenmark/DaSSCo-asset-service/files/13228100/DocumentedIssuesForAPI.docx)

##  What is the issue ?
When using (mainly the update) parts of the API many fields does not have their data updated/shown accordingly. 
Part of the documentation from Northtech does not match up very well with reality. 

# Detailed description of the issue. 

There are multiple fields that does not update when using the API. This has been tested with postman. 
For example digitizer and update user fields. 
Currently we cannot add "TXT" files to the payload field despite it saying so in the documentation. 

There are multiple fields that are confusing through missing documentation. Sometimes its non existing or lacking other times its just wrong. 
For example there are fields where we dont know what kind of responses we can expect.

It makes working with the API difficult since you cant fully predict what happens at each step. 

There are some parts of the issues that currently would make automatization nearly impossible.

There are documented examples of the problems added in an attached document. This document is likely not an exhaustive list of all issues. 

## Estimate level of effort required.

# medium - depends on northtech 

## What is the expected acceptable result.

We can use the api to update/create the fields we wish.
The documentation reflects what the api does.

**Comment by Baeist** [comment]
Certain aspects seems to be working better than described in the above. However the documentation still makes it very hard to understand and use properly. There are also still some of the touched upon areas that appear bugged. 
Our own most current documentation for the metadata fields are not the ones used by NT as far as i can tell. Possibly they have not received it?
Uploading updated api issues along with newest metadata version i could find.

[NorthTechApiIssue .txt](https://github.com/NHMDenmark/DaSSCo-asset-service/files/13281340/NorthTechApiIssue.txt)



[Metadata_v4.xlsx](https://github.com/NHMDenmark/DaSSCo-asset-service/files/13281342/Metadata_v4.xlsx)

**Comment by Baeist** [comment]
| Issue                                                 | COMMENTS |
|----------------------------------------------------------------------------------|
| Correct API documentation.             | Documentation for the API use needs to be up to date. 
| Update asset            | The update functionality does not correctly update every field. You cant update the specimen_barcodes field or digitiser fields. This can appear as if its working but when getting the asset later changes are not showing there. 
| Get asset | Does not show speciment_barcodes field. It does show the specimens field which is not an option when you create an asset.
| Update w. pipeline | You "can" update an asset with a pipeline that does not exist. You get  a status 200 back but the asset has not actually updated.
| List "file_formats" field | The inputs that are allowed here are TIF, JPG and RAW. Documentation names several other options.

**Comment by Baeist** [comment]
| Issue                    | COMMENTS                                                                                               |
|--------------------------|--------------------------------------------------------------------------------------------------------|
| Update asset              | The update functionality does not correctly update every field. You can't update the  `asset_pid` or `digitiser` fields. This can appear as if it's working, but when getting the asset later, changes are not showing there. |
| Update w. pipeline        | You "can" update an asset with a pipeline that does not exist. You get a status 200 back, but the asset has not actually updated. |
| List "file_formats" field | The inputs that are allowed here are TIF, JPEG, and RAW. Documentation names several other options.    |
| Asset_taken_date field        | This information disappears when creating or updating an asset. |
| Asset_pid field        | This is stated as being required in the documentation. You can create an asset without it. |
| Specimens protocol        | The institution and collection fields cant be created or updated. They only show up in response but when using get asset later. |
| Status 500       | When trying to get asset "42" or create "42" status 500 happens. I dont know how to reproduce this. |

**Comment by k-zamzam** [comment]
| Issue | Comments |
| ------------- | ------------- |
| Asset_pid field | It is stated in the documentation that this field is unique. However, I'm able to create assets with the same asset_pid  |
| Strange error messages | When I try to create an asset with a pipeline that does not exist in the given institution, I get the error message "Asset doesnt exist!". The error messages should be more clear. For example: "The pipeline "ldpip" does not exist in the institution "ld"|

**Comment by Baeist** [comment]
| Issue                    | COMMENTS                                                                                               |
|--------------------------|--------------------------------------------------------------------------------------------------------|
| NEW List available files              | "https://storage.test.dassco.dk/file_proxy/api/file_proxy/api/assetfiles/test-institution/test-collection/asset_18/postman.txt" it returns faulty urls. There are "file_proxy/api" twice in a row. |

**Comment by Baeist** [comment]
| Issue                    | COMMENTS                                                                                               |  Done |
|--------------------------|--------------------------------------------------------------------   |------------------------------------|
| List available files  / List file info            |  | |

**Comment by Baeist** [comment]
@bhsi-snm @k-zamzam 
| Issue                    | COMMENTS                                                                                               |  Done |
|--------------------------|--------------------------------------------------------------------   |------------------------------------|
| NEW List available files              | "https://storage.test.dassco.dk/file_proxy/api/file_proxy/api/assetfiles/test-institution/test-collection/asset_18/postman.txt" it returns faulty urls. There are "file_proxy/api" twice in a row. |  |
| "pipeline_name" and "workstation_name" fields   | These should be correctly named as such but in the actual api they are just pipeline and workstation. |  |
| List available files  / List file info     | These do not match. I can have 2 files shown in available files and 4 in list file info.  | |
| Change allocation   | I cant change the allocated space for asset_27. Getting these values in the response: proxy_allocation_status_text": "Size of files in share is greater than the new value", "http_allocation_status": "ILLEGAL_STATE", For the size being larger that is straight up wrong. Maybe its a conversion issue with bytes and megabytes. For reference this is the response body from when the share was opened: {  "path": "/assetfiles/test-institution/test-collection/asset_27/", "hostname": "https://storage.test.dassco.dk/file_proxy/api", "total_storage_mb": 75000, "cache_storage_mb": 2000, "all_allocated_storage_mb": 8247, "remaining_storage_mb": 64753, "allocated_storage_mb": 1200, "proxy_allocation_status_text": null, "http_allocation_status": "SUCCESS", "parent_size_mb": 0}. 
"allocated_storage_mb": 0 how is this possible after getting a "http_allocation_status": "SUCCESS" from {"asset_guid": "{{metadata-new-guid}}",    "new_allocation_mb": 5} , example /assetfiles/test-institution/test-collection/test-asset-guid-14/| |

It generally seems that the longer i work with an asset and upload/delete/open share/sync erda the more likely i am to end up with an asset that cant be interacted with anymore. The exact steps for this seems a bit random.

**Comment by Baeist** [comment]
@bhsi-snm @k-zamzam 
| Issue                    | COMMENTS                                                                                               |  Done |
|--------------------------|--------------------------------------------------------------------   |------------------------------------|
| NEW List available files              | "https://storage.test.dassco.dk/file_proxy/api/file_proxy/api/assetfiles/test-institution/test-collection/asset_18/postman.txt" it returns faulty urls. There are "file_proxy/api" twice in a row. |  |
| "pipeline_name" and "workstation_name" fields   | These should be correctly named as such but in the actual api they are just pipeline and workstation. |  |
| Change allocation   | I cant change the allocated space for asset_27. Getting these values in the response: proxy_allocation_status_text": "Size of files in share is greater than the new value", "http_allocation_status": "ILLEGAL_STATE", For the size being larger that is straight up wrong. Maybe its a conversion issue with bytes and megabytes. For reference this is the response body from when the share was opened: {  "path": "/assetfiles/test-institution/test-collection/asset_27/", "hostname": "https://storage.test.dassco.dk/file_proxy/api", "total_storage_mb": 75000, "cache_storage_mb": 2000, "all_allocated_storage_mb": 8247, "remaining_storage_mb": 64753, "allocated_storage_mb": 1200, "proxy_allocation_status_text": null, "http_allocation_status": "SUCCESS", "parent_size_mb": 0}. | |
| Change allocation      | After updating allocation this can happen- "allocated_storage_mb": 0 how is this possible after getting a "http_allocation_status": "SUCCESS" from {"asset_guid": "{{metadata-new-guid}}",    "new_allocation_mb": 5} , example /assetfiles/test-institution/test-collection/test-asset-guid-14/| |
| Get in progress assets     | Returns status 500 internal server error.  | |
| Create asset     | Requires asset_pid to have more than an empty string. Documentation on confluence does not support this. | |
| Create asset   | Payload is a string, we have it as a list of strings. | |

If a share is opened multiple times it will cause: 
{
    "type": "Error",
    "protocolVersion": "1.0",
    "errorCode": "BAD_REQUEST",
    "errorMessage": "No writeable share for asset found"
}, which makes the asset unable to be further synced. This is an issue if others are going to be using the api. There is no status currently that tells whether a share is opened for an asset.
