### ISSUE TITLE
"allocation_status_text" field

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-asset-service#32]
The "proxy_allocation_status_text" does not have clear naming throughout.
From change allocation:
{
    "path": "/assetfiles/test-institution/test-collection/second0002/",
    "hostname": "https://storage.test.dassco.dk/file_proxy/api",
    "total_storage_mb": 75000,
    "cache_storage_mb": 2000,
    "all_allocated_storage_mb": 13767,
    "remaining_storage_mb": 59233,
    "allocated_storage_mb": 0,
    "proxy_allocation_status_text": null,
    "http_allocation_status": "SUCCESS",
    "parent_size_mb": 0
}
From create asset:
"httpInfo": {
        "path": "/assetfiles/test-institution/test-collection/test-asset-guid-22/",
        "hostname": "https://storage.test.dassco.dk/file_proxy/api",
        "total_storage_mb": 75000,
        "cache_storage_mb": 2000,
        "remaining_storage_mb": 59257,
        "allocated_storage_mb": 1,
        "allocation_status_text": null,
        "http_allocation_status": "SUCCESS"
    },
From open share:
{
    "path": "/assetfiles/test-institution/test-collection/test-asset-guid-13/",
    "hostname": "https://storage.test.dassco.dk/file_proxy/api",
    "total_storage_mb": 75000,
    "cache_storage_mb": 2000,
    "all_allocated_storage_mb": 13768,
    "remaining_storage_mb": 59232,
    "allocated_storage_mb": 1,
    "proxy_allocation_status_text": null,
    "http_allocation_status": "SUCCESS",
    "parent_size_mb": 0
}
The documentation names the field as http_allocation_status_text or http_allocation_text. 
@NTechThomas  @k-zamzam @bhsi-snm

**Comment by NTechThomas** [comment]
I will rename it so they both have the name `allocation_status_text`
