### ISSUE TITLE
Negative allocation when opening share

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-asset-service#33]
@NTechThomas  @bhsi-snm 
Not really sure how this is actually working but it is. The file and the share seems to behave normally after this. 
You cant change the allocation to an amount that is less than the actual file size after but you can open the share with less. You cant open a share with size 0 though.
{
    "path": "/assetfiles/test-institution/test-collection/second0002/",
    "hostname": "https://storage.test.dassco.dk/file_proxy/api",
    "total_storage_mb": 75000,
    "cache_storage_mb": 2000,
    "all_allocated_storage_mb": 13772,
    "remaining_storage_mb": 59228,
    "allocated_storage_mb": -1,
    "proxy_allocation_status_text": null,
    "http_allocation_status": "SUCCESS",
    "parent_size_mb": 0
}

**Comment by NTechThomas** [comment]
I have updated it to reject negative allocations too. It will be included in the bugfix release next friday.
