### ISSUE TITLE
Parent files for derivatives

### ISSUE THREAD

**Issue by Baeist** [NHMDenmark/DaSSCo-asset-service#39]
When creating an asset that is a derivative are the parents files supposed to be added to the file share of the derivative? It says in the meeting notes that when creating an asset without a parent that there should be no attempt to download the files from erda which would imply that creation of an asset with a parent would attempt to. Could we have this clarified? 

@bhsi-snm @NTechThomas

**Comment by Baeist** [comment]
[ Open share without parent files](https://go.screenpal.com/watch/cZfDIIVsseW)

**Comment by bhsi-snm** [comment]
is this done @Baeist can we close it?

**Comment by Baeist** [comment]
Yes. We needed clarification that the parent guid should be present in the request body when opening a share.
