### ISSUE TITLE
Detailed View

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#49]
We need a detailed view for an asset, where we can look at the metadata. Something like this:

![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/43371699/223a7d8a-3113-4b83-a0f7-0383e1411157)
(This is only a quick sketch, not the final design) 

We would usually arrive at this page from a search or through an asset group (both are just lists of assets). I should always be able to go back to these views without breaking the search query etc.

This task is only the "viewing" of the asset, we will add a few things to this view later on. Both download functionalities and edit view, those tasks can be found here:
1. [Download metadata](https://github.com/NHMDenmark/DaSSCo-asset-service/issues/50)
2. [Download files](https://github.com/NHMDenmark/DaSSCo-asset-service/issues/51)
3. [Edit Asset Metadata](https://github.com/NHMDenmark/DaSSCo-asset-service/issues/53)

**Acceptance Criteria**
- [x] We have a detailed view of assets
- [x] We can deeplink to an assets detail view
- [x] Tested locally 

Updated 17/06:

- When accessed from a list of assets, the view shows the asset selected, and has buttons to go back and forth to see the detailed view of different assets.
- Back button from the browser goes back to the list of assets.

**Comment by Nicolas-Northtech** [comment]
![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/170070638/63c01e5c-47d8-4f35-a6d3-62ac5fc5066b)

Detailed view currently looks like this. It gets the asset_guid from the URL and gets all the information based on that afterwards. If the asset_guid does not exist, it tells the User.

**Comment by bhsi-snm** [comment]
Some questions regarding the detailed view: 
Is it able to show all the metadata fields?
I noticed the tasks about the following but the UI doesn't reflect that it is possible, therefore asking these questions.

Is it possible to go back to search from a detailed view?
Is it possible to scroll in a detailed view between search results?

Comments:
We want the photo to be on the right side.
use as less real estate as possible for the view.

**Comment by Nicolas-Northtech** [comment]
- The detailed view right now has all the metadata in the right panel (you can scroll to see what you need). It would be nice to get a prioritization of the fields (what are the most important fields you want to see always without scrolling, maybe institution or collection?).
- It will be possible to get back to the search (saved) from this view.
- It is not possible right now to scroll between search results, but it can be done if that is what you want.
- Will move the picture to the right side.
- Can you tell me a little better in detail about the space? This is a different page from the search, so the entire page is available for the view.

**Comment by Nicolas-Northtech** [comment]
- Picture is on the right.
- View now has two buttons in the bottom to go back and forth between assets in the list.
- Using the browsers back button goes to the previous page (independently of how many assets you viewed).

**Comment by Nicolas-Northtech** [comment]
Blocked until we can connect with search page.

**Comment by Nicolas-Northtech** [comment]
Changed what was talked in the meeting: Asset Metadata now has more space, and files are shown less.
Added differentiation between the titles and the parameters in the asset metadata for clarity.
Only thing missing is the connection with Frontend.
