### ISSUE TITLE
Bulk Update Asset Metadata

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#54]

**Comment by Nicolas-Northtech** [comment]
@bhsi-snm following up on yesterday's meeting, I remember we decided on letting most of the parameters in assets to be bulk updateable, with some exceptions. I would need a list as soon as you can provide it to start with that. Later today I will make available a prototype for the UI, so we can decide the looks of it.

**Comment by Nicolas-Northtech** [comment]
![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/170070638/a7979740-a19f-431a-bd76-dc67cc8e31f5)

The UI so far: 

- The list of properties is the one that I have working right now (tags, specimens, status, asset_locked, subject, restricted_asset, funding, formats, payload_type and parent_guid). 
- The image shows the different ways to input the data: Input fields for strings, select for when we need to pick one option from a list, and checkboxes for when we might need more than one option. 
- The tag section has a list of tags being added, the red x means that they can also be deleted if a mistake was made (it shows only the tag name, not the description). Similar functionality exists for the Specimens (it will show the specimen barcode in the list).
- The sections are independent to let the person doing the editing decide what they want to edit easily without having to scroll too much. 

Looks are of course not final. Feedback is appreciated. 

@bhsi-snm

**Comment by Nicolas-Northtech** [comment]
Blocked until final list of updateable fields on the Asset is provided, same with UI feedback.
Current working solution ready for a demo.

**Comment by bhsi-snm** [comment]
We want all the fields except ARS system-generated fields of the metadata to be updatable in bulk.
The access control which will come later in another version will then be able to restrict, who can update which field.  

Some comments on the UI:
Looks nice - is it correctly understood that the follow is: 

1. Search 
2. get list of results out
3. Click on bulk update,
4. has an option to select if wanna bulk update all or some of the search results.
5. Then it is possible to see this view

Some comments on the UI:
Restricted Access is not related to access control - it is to determine if it should be published on the web or not
When we update - are we able to see exisitng value and changed value simulateously?
What if some records have different values for the same field ?
How do we handle that?
 
We would like a review pane before hitting confirm on the bulk update where the user can review the bulk changes one last time before it is commited.

**Comment by Nicolas-Northtech** [comment]
- Yes, you are correct. We will get to this page from the Search page.
- Viewing the existing data is not possible in this version. We would need to discuss if that is something you need, as it can get out of hand when trying to update many assets. Remember that what the bulk update does is replace all existing data with the data that we pass in this view, if it's same or different does not matter. Let's take for example the Preparation Type. If some assets have one type, other assets have a different one, and you decide to put a new one in the Bulk Update page, then it will replace all of the assets with that new preparation type. - Understood on the review pane, will do.

**Comment by bhsi-snm** [comment]
Agreed we can live without the the existing values of the metadata fields but would like to see the enumerated list with what is a possible value for the fields that have enums.

**Comment by Nicolas-Northtech** [comment]
The fields that have enums (restricted asset, file format) all have the checklist to decide which of the ones on the list you want to add.

**Comment by Nicolas-Northtech** [comment]
Tags are now added (not replaced). Removed specimens from being bulk-updateable, as well as file_formats and restricted_access.
Feature ready for Demo, just waiting on connection to search engine.

**Comment by Nicolas-Northtech** [comment]
Added Confirmation pop up before bulk updating.
Only thing lacking is the connection to the Query page.
