### ISSUE TITLE
Statistic Dashboard - Graph is "too responsive"

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#56]
We're having issues when zooming on the graph, it seems to be way too responsive. And it's very difficult to to "return to the original zoom lvl", there's a button for it but it doesn't work for custom date ranges.

*Not zoomed*
![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/43371699/9160a1da-2b1c-4940-9ea9-6264077f326b)

*Zoomed out, and then in again*
![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/43371699/b50559f7-70b8-490b-a030-fe260593cc30)

I see 2 ways to fix this, either changing the zoom mode to 'x' instead of 'xy'. That way you wont be able to zoom on the Y axis and only zoom on the X axis, we can't slow it down but this way it's still useable.

The other way is to disabling zoom on the graph view.

Let's try the first option, and show it to Bhupjit or Pip. If it's still too aggressive then, I would suggest disabling it.

**Acceptance Criteria**
- [x] We no longer have issues with the graph going "off-scale"
- [x] Tested locally

**Comment by Nicolas-Northtech** [comment]
Changed zoom to x axis, solves the issue with the graph going off-scale.
