### ISSUE TITLE
Search Engine - Sort Result List

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#57]
Once I've searched for assets in the "Search Engine", I should be able to sort it based of different fields in the metadata in ascending or descending order.

Fields to view and sort on:
- Institution 
- Collection 
- Barcode (Specimen)
  - The barcode belongs to the specimen. An asset can potentially have more than one speicmen. 
    - If there is more than one barcode, sort on the first one in the list
- Date_asset_taken
- Date asset_created 
- File_format
  - Sort via list of file fomat enums

**Acceptance Criteria**
- [x] I can sort the result list in a ascending/descending order based on a metadata field
- [x] Tested locally

**Comment by Grand666** [comment]
Hi @bhsi-snm and @PipBrewer 

Have you had time to look at the fields you want to sort on in the Result Table? (Search Engine)

**Comment by bhsi-snm** [comment]
Columns as output of search as well as for sorting

Institution - already there
Collection - already there
Barcode
Date_asset_taken - is this Created date?
File_format -already there (edited)
