### ISSUE TITLE
Search Engine - Save Search

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#58]
I should be able to save "Search Queries" as reports in the "Search Engine", that way it'll be easier to revisit the search later on. A case could be, that I as a collection manager I want check how many new assets has been created in my collection and I need to check it more than once. It would make my life easier to able to use an earlier query I created instead of rewriting it every time I have to check it.

A saved search should be a new "node" in the database, it should be connected to the User that created it. 

You should be able to give the saved query a name and update it afterwards.

You should be able to delete the saved search

Saving you own personal searches only requires read access.

Remember to validate the persons access to the asset, so we only return assets the User has access to.

**Acceptance Criteria**
- [x] I am able to save a Search Query to reuse it later
- [x] I can give it a name and update it
- [x] I can delete the saved search
- [ ] Assets I don't have access to, does not shown up in the search
- [ ] Tested Locally

**Comment by Hayleene** [comment]
Hey, I'm searching for the best dark web search engine nowadays that offers ultra privacy and security. With the increasing need for anonymity and secure browsing, I want to find a reliable search engine that prioritizes user safety. Can anyone recommend this kind of [dark web search engine](https://openindexsearch.com/) that excels in protecting user data and ensures encrypted connections? I'm particularly interested in one that has a good reputation for privacy, minimal tracking, and robust security features.

**Comment by mvb-nt** [comment]
Currently blocked. Awaiting the access feature to be built before we can finish this task.
