### ISSUE TITLE
Bulk Export Asset Metadata as CSV

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#59]
It should be possible to download metadata of multiple assets as a CSV file.

1. After I've searched for assets in the "Search Engine", it be possible to select multiple assets and download their metadata as CSV
2. On an Asset Group it should be possible to select multiple of the assets and download their Metadata as CSV

**Acceptance Criteria**
- [x] I'm able to download multiple the metadata of multiple assets
- [x] I can select multiple assets from the "Search Engine" and download their metadata as CSV
- [x] I can select multiple assets from an Asset Group and download their metadata as CSV
- [x] I'm only able to the download the metadata of the assets, that I have access to
- [x] Tested Locally

**Comment by Nicolas-Northtech** [comment]
Bulk Asset Metadata can be downloaded from the Query page. 
User passes a list of asset guids -> Check to see if they exist, and if the User has read access to them -> Creation of a csv file in a temp folder, prompt for download and deletion of temp folder.

Only thing missing is the same functionality in the asset group frontend, will do bulk download zip files and then come back to this in hopes that the frontend will be done or close to be done by then.

**Comment by Nicolas-Northtech** [comment]
Finished, user can download the information about assets from the asset group page.
