### ISSUE TITLE
Bulk Download Asset Images together with metadata

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#60]
It should be possible to download the multiple "complete" assets.

"complete asset" means the asset files and the metadata for the selected asset, I would expect a zip folder with a CSV file and folders with the assets GUID as name, inside these folders will be the files of the particular asset:

![Image](https://github.com/NHMDenmark/DaSSCo-asset-service/assets/43371699/38cebb03-02bb-4f59-84cf-5a378eea537c)

1. When I have searched for assets in the "Search Engine" it should be possible to select assets, and download the "complete" asset as a zip folder.
2. When I go to an asset group, I should be able to select assets in the group and download "complete" asset as a zip folder.

**Acceptance Criteria**
- [x] I'm able to download the files of multiple "complete" assets as zip folder
- [x] I can select and download "complete" assets I found with the Search Engine
- [x] I can download the "complete” assets from a Asset Group I have access to
- [x] I'm only able to the download the "complete" assets, that I have access to
- [x] Tested locally

**Comment by Nicolas-Northtech** [comment]
Modified functions for creating and downloading ZIP files to allow for a list of assets. This works both in Queries page and Detailed View.
Tested locally, complains when a person does not have access to an asset and tells which assets are the problematic ones.

**Comment by Nicolas-Northtech** [comment]
Missing implementation on Asset Groups frontend.

**Comment by Nicolas-Northtech** [comment]
Added implementation on Asset Group frontend.
