### ISSUE TITLE
Create Asset Groups - Backend

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#62]
Based on a search, it should be possible to select multiple assets and create an "Asset Group". You will later on be able to view this group, add and remove assets from the group. (You need at least Read Role to the assets)

When viewing the group, you should be able to do both Bulk Update and single updates to Assets Metadata. (Given you have write access to the assets)

1. Create Group
2. Remove Group
3. Update Group
4. List Groups

**Acceptance Criteria**
- [x] You're able to create Asset groups
- [x] You can add and remove assets from the group
- [x] Tested locally
- [x] Create Unit tests
- [x] Create Integration tests in the Test Suite

**Comment by Nicolas-Northtech** [comment]
Main functionality is working and tested, I need a little bit more of information about read/write access before I can definitely finish it.

**Comment by Nicolas-Northtech** [comment]
![Image](https://github.com/user-attachments/assets/9cbcbd1d-7422-4f4e-befd-1a4542ad625f)

In the image we can see that there are two institutions with a collection. Institution 3 is restricted to role-1, so the collections, specimens and assets under it will also be restricted to that role. Institution 4 has a collection which is restricted to role 2. Only the specimens and assets from that collection will be restricted to that role.
This collections have assets, and those assets have been grouped with the asset group "moths". That asset group has been created by nicolas, and the user role-1-user has access.

Now, the graph does not show it exactly, but what happens here is that now that role-1-user has access to the "moths" group, now it has temporary reading permission, so it can read asset 4 (from institution 4, which has the assets restricted to role-2).
This read access is temporary and upon deletion of the asset group or removal of the user from the group the user will no longer have the permission to read that asset. In this case, the user that created the asset group is either a service user or has reading permission for both roles 1 and 2.

**Comment by Nicolas-Northtech** [comment]
Re-opened issue.
We need to return a list of assets that the User does *not* have Write access to, when trying to grant access to an asset group. Just so the user can have a bit more information about why the granting didn't work and how to fix it.

**Comment by Nicolas-Northtech** [comment]
Done. When creating Asset Groups with/without permission, if there's an Asset that the User does not have access to it, returns 403 + information about the failing asset.
Same functionality for adding assets to asset group and granting permission to asset group.
This way the user has information on what to do to fix the error.
