### ISSUE TITLE
Make the Test Suite Configurable

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#63]
In order to use the test-suite on both the test environment and whenever we work locally, we need to be able to change the Hostname for Keycloak, FileProxy and the AssetService. We also need to be able to change the client_id and client_secret for the service user used when logging in.

List of environment specific variables:
- Keycloak hostname
- Client Id
- Client Secret
- Asset Service hostname
- File Proxy hostname

**Acceptance Criteria:**
- [x] Has been tested on the Test env
- [x] Has been tested on the local env
- [x] We can configure the environment specific variables

**Comment by Nicolas-Northtech** [comment]
Blocked by not being able to test yet on the Test env
