### ISSUE TITLE
ERDA Connection Error

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#64]

**Comment by bhsi-snm** [comment]
ERDA says 16 parallel connections are possible and I have checked with the share link on dasscoapp02 with 6-8 parallel connections and it seems to be working. 
My best guess is that there is a timing issue where it might be recommended to add a small delay- duration can be found with hit and trial.
ERDA support has mentioned that if we try to establish more than 16 parallel connections, the ip address gets blocked and the firewall also blocks when too many connections get open in a short period of time. 
I am in process of finding out what is too many and what is a short period of time.
