### ISSUE TITLE
Save Asset Service and File Proxy logs in a Persistant Volume.

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#66]
We need to save the logs in a persistant volume, so we're able to read them KU IT restarts the Docker Swarm.

Both Access Log and Stdout should be save for both applications.

**Acceptance Criteria** 

- [x] Asset Service now saves the logs in a folder - /logs
- [x] File Proxy now saves the logs in a folder - /logs
- [x] Tested locally

**Comment by Nicolas-Northtech** [comment]
Added logback.xml file to resources folder:

`<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="ROLLING_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>target/logs/stdout.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>30</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%date{HH:mm:ss} %-5level %logger{35} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="ROLLING_FILE" />
    </root>

</configuration>`

Then, on application.properties file:

`logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)
server.tomcat.basedir=target
server.tomcat.accesslog.directory=logs/
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.max-days=30`

Both projects have the same configuration.

Next, in Docker:

docker-compose file: Add this at the same level as services:
`volumes:
  log-volume:
  asset-service-log-volume:`

docker-compose-app:
    `volumes:
      - ./private.pem:/private.pem
      - log-volume:/target/logs`

docker-compose-asset-service-app:
   ` volumes:
      - asset-service-log-volume:/target/logs`

For this to work all the containers have to be in the same network.
