### ISSUE TITLE
Statistic Dashboard - Add Refresh

### ISSUE THREAD

**Issue by Grand666** [NHMDenmark/DaSSCo-asset-service#68]
We would like to be able to refresh the data presented in the graph, without it resetting our custom ranges.

I suggest 2 things:

1. Add the graph params to the params in the browser, that way it will possible to refresh the data using "F5", but also bookmark or share links to the graph.
2. Add a small refresh button next to the graph, that refreshes the data.

**Acceptance Criteria**
- [x] Tested Locally
- [x] I can deeplink to a graph view with settings
- [x] I can refresh the data using "F5"
- [x] I can refresh the data using the new refresh button

**Comment by Nicolas-Northtech** [comment]
The graph now creates a url with /:startDate/:endDate/:statValue (this means if you want to see specimens/Institute, specimens/Pipeline or specimens/Workstation). 
So, it is now possible to deeplink to a graph with a custom date and a set statValue. If an incorrect url is passed the main specimen page (one week time range, specimens/institution) is shown instead.
