### ISSUE TITLE
ARS Search Engine - Cache Backend

### ISSUE THREAD

**Issue by mvb-nt** [NHMDenmark/DaSSCo-asset-service#73]
All properties fit for a dropdown should be cached in the backend, so that we have fast access to them.

List:
- asset_created_by
- asset_deleted_by
- asset_updated_by
- audited_by
- digitiser
- metadata_created_by
- metadata_updated_by
- metadata_uploaded_by

Non-names which should be drop downs:
- Asset_subject (list)
- Audited (boolean)
- Collection (list)
- Institution (list)
- Multispecimen (boolean)
- Payload_type (list)
- Pipeline_name (list)
- Preparation_type (list)
- Restricted_access (list)
- Status (list)
- Workstation_name (list)

**Acceptance Criteria**
- [x] Works locally

**Comment by bhsi-snm** [comment]
List of metadata fields that should be drop down selections for searches

asset_created_by
asset_deleted_by
asset_updated_by
audited_by
digitiser
metadata_created_by
metadata_updated_by
metadata_uloaded_by
 
Non-names which should be drop downs:
Asset_subject
Audited
Collection
Institution
Multispecimen
Payload_type
Pipeline_name
Preparation_type
Restricted_access
Status?
Workstation_name


@Nicolas-Northtech 
How will name fields work? Will they produce a list of drop down options or searchable text box?
Is there a limit on no of values for cache?
Is the cache time customisable from UI?
Is there a way to force a refresh of cache ?

**Comment by Nicolas-Northtech** [comment]
Institution, Collection, Pipeline, Workstation, Digitiser, Subject, Payload Type, Preparation Type, Status List and Restricted Access now have caches. 
The cache is loaded on application start, and updated every time there's a change (new Institution creation, new Asset with a Status not present in the cache, etc).
If I recall correctly, we discussed that the fields are going to be somewhat limited (we don't expect to have a million different Statuses, for example), so the cache does not have a set time. Theres also no need to force a refresh of cache, as it is done automatically if anything relevant for the cache changes.
To answer your other questions: The name fields will work as autocompletes and not dropdowns and there is currently no limit for the number of values in the cache, but as I said before we are expecting those fields to have a manageable number of values.
