### ISSUE TITLE
ARS Search Engine - Cache Frontend

### ISSUE THREAD

**Issue by mvb-nt** [NHMDenmark/DaSSCo-asset-service#74]
We want to cache the query in the frontend, not the results for now, but just the construction of the query. So that we don't throw it away if you accidentally refresh the site.

To get the results again, the user will have to press the search button again.

We will cache the properties of each node, but we will set an expiry time for this cache (1 hr).

**Acceptance Criteria**
- [ ] The query is cached and the forms are filled out upon reload
- [ ] Node properties are cached for an hour
- [ ] Tested locally

**Comment by mvb-nt** [comment]
@bhsi-snm I'm soon through with this task except for the dropdown values we need from Pip - as mentioned briefly at the status meeting today. Let me know if/when you guys have had the time to take a look at them and they're ready. :)

**Comment by bhsi-snm** [comment]
List of metadata fields that should be drop down selections for searches

asset_created_by
asset_deleted_by
asset_updated_by
audited_by
digitiser
metadata_created_by
metadata_updated_by
metadata_uloaded_by

Non-names which should be drop downs:
Asset_subject
Audited
Collection
Institution
Multispecimen
Payload_type
Pipeline_name
Preparation_type
Restricted_access
Status?
Workstation_name

@Nicolas-Northtech @mvb-nt 
How will name fields work? Will they produce a list of drop down options or searchable text box?
Is there a limit on no of values for cache?
Is the cache time customisable from UI?
Is there a way to force a refresh of cache ?
