### ISSUE TITLE
ARS Search Engine - JSON Compression

### ISSUE THREAD

**Issue by mvb-nt** [NHMDenmark/DaSSCo-asset-service#75]
We will be sending large amount of data in the Search Engine, so  to speed up the response from the server, we should enable data compression. This means all json responses will be compressed, this should not effect running integrations only make them faster.

This should be add `server.compression.enabled=true` to the application.properties file. 

**Acceptance Criteria:**
- [x] The integration test suite still succeeds (locally)
- [x] The responses are now compressed (check via postman for data transferred)
- [x] Works locally

**Comment by Nicolas-Northtech** [comment]
Done. 
Just FYI if we need to do it again, Postman actually doesn't show the change between not compressed and compressed, we are better checking in the browser if the response has Content-Encoding: gzip or not.
Also worth noting that only things bigger than 2kb will get compressed (can be changed).
