### ISSUE TITLE
ARS Search Engine - Frontend updates

### ISSUE THREAD

**Issue by mvb-nt** [NHMDenmark/DaSSCo-asset-service#78]
We can get a lot of results from our search queries, so to get a nice overview, we will setup a pagination table for the results. 

When we search, we send a limit with the query so we don't poll too much data out accidentally. But we still want to know, and show, the total number of assets found by the query even if we don't show them all in the frontend.
_(Proposed layout addition for this feature:
Show a loading icon while the query count is running, for cases where the full amount of queries is so high that it takes a while to read.)_

Blocked: waiting for the fields list from Pip/Bhupjit
We have a lot of fields that should be shown as "dropdowns", but we also want to be able to search in the suggested values, meaning it should be an autocomplete. 

List of metadata fields that should be drop down selections for searches

- asset_created_by
- asset_deleted_by
- asset_updated_by
- audited_by
- digitiser
- metadata_created_by
- metadata_updated_by
- metadata_uloaded_by

Non-names which should be drop downs:

- Asset_subject
- Audited
- Collection
- Institution
- Multispecimen
- Payload_type
- Pipeline_name
- Preparation_type
- Restricted_access
- Status?
- Workstation_name

The operators of the queries should be set as "=" if it's an enum/autocomplete like the above or statuses, etc. 

**Acceptance Criteria**
- [x] We have pagination on the results table
- [x] We can see the total count for a query, even if we limit it to a lower amount
- [x] We've changed some of input fields to Autocompletes (dropdown)
- [x] "=" is the only usable operator when working with properties using enum values
- [ ] Tested locally

**Comment by Grand666** [comment]
Hi @bhsi-snm,

We have thought a bit about this:

"When we search, we send a limit with the query so we don't poll too much data out accidentally. But we still want to know, and show, **the total number of assets found by the query** even if we don't show them all in the frontend."

Would it be fine if we limit the count to 10.000? So in the UI it will just show 10.000+

It can be quite "expensive" for the database to run through millions of records just to get a count, when it's only used purpose. If you actually just want a count and you're not interested in the metadata for a specific query, I think we should do it in some other way.

In theory we could just do a full count every time, but in some cases it will take a lot of time to get the count and it will use a lot of the database resources.

Let me know if it makes sense and if this is good enough.

**Comment by PipBrewer** [comment]
10,000 seems reasonable, as long as it is not impossible to keep getting additional results. And for it to give a reliable count up to 10,000 and after that it says 10,000+

Regarding the count, I can imagine using this on 5-10 occassions per year to generate results for specific (and changing queries) for management and reports. I probably would not need the results of the query. However, it is not possible to always predict what these queries to get the results would be (they would change). It also needs to be something that can be done by someone like me (i.e., a non-programmer). What are your suggestions?
